[package]
name = "flume-bug-reproducer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
flume = "0.11.0"
num_cpus = "1.16.0"
tokio = { version = "1.39.1", features = ["full"] }